export const queryKeys = {
  user: "user",
  loginUser: "loginUser",
  userFeed: "userFeed",
  userFeedPost: "userFeedPost",
  post: "post",
  writerInfo: "writerInfo",
  postLikeState: "postLikeState",
  comment: "comment",
  followerList: "followerList",
  followList: "followList",
  deletePost: "deletePost",
  commentReply: "commentReply",
  searchUsers: "searchUsers",
  chatList: "chatList",
  chatDetail: "chatDetail",
  chatHistory: "chatHistory",
  chatPaginated: "chatPaginated",
  diaryMember: "diaryMember",
};
