export const queryKeys = {
  user: "user",
  userFeed: "userFeed",
  userFeedPost: "userFeedPost",
  post: "post",
  writerInfo: "writerInfo",
  postLikeState: "postLikeState",
  comment: "comment",
  followerList: "followerList",
  followList: "followList",
  deletePost: "deletePost",
  commentReply: "commentReply",
  searchUsers: "searchUsers",
  chatList: "chatList",
};
